version: '3.7'

services:
  web:
    image: luissaybe/luissaybe
    command: nginx -c /root/project/docker/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/root/project
