services:
  install:
    image: luissaybe/luissaybe
    command: ["npm", "install"]
    volumes:
      - .:/root/project
  vite:
    image: luissaybe/luissaybe
    command: ["npx", "vite"]
    ports:
      - "5173:5173"
    volumes:
      - .:/root/project
    depends_on:
      install:
        condition: service_completed_successfully