services:
  install:
    image: luissaybe/luissaybe
    command: ["npm", "install"]
    volumes:
      - .:/root/project
  serve:
    image: luissaybe/luissaybe
    command: ["npx", "serve", "-p", "80", "src"]
    ports:
      - "80:80"
    volumes:
      - .:/root/project
    depends_on:
      install:
        condition: service_completed_successfully
